CREATE TABLE PRODUCT (
    ID BIGINT NOT NULL,
    NAME VARCHAR(25),
    PRICE DECIMAL(10, 2),
    MARCA VARCHAR(15),
    STATUS CHAR(1),
    IMAGE VARCHAR(30),
    ESPECIF TEXT,
    SUB_CATEGORY_ID BIGINT NOT NULL,
    PRIMARY KEY (ID)
) ENGINE=InnoDB;
