-- Adicionando a chave estrangeira da tabela SUB_CATEGORY para a tabela CATEGORY
ALTER TABLE SUB_CATEGORY
    ADD CONSTRAINT FK_SUBCATEGORY_CATEGORY FOREIGN KEY (CATEGORY_ID)
    REFERENCES CATEGORY(ID);

-- Adicionando a chave estrangeira da tabela PRODUCT para a tabela SUB_CATEGORY
ALTER TABLE PRODUCT
    ADD CONSTRAINT FK_PRODUCT_SUBCATEGORY FOREIGN KEY (SUB_CATEGORY_ID)
    REFERENCES SUB_CATEGORY(ID);